# Generated by Django 5.1.1 on 2024-10-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('create_data', models.DateTimeField()),
                ('update_data', models.DateTimeField()),
                ('content', models.TextField()),
                ('numbers_of_likes', models.IntegerField()),
            ],
        ),
    ]
